Create all entities
auto-ckz/auto-ckz pull request #4
Opened 2016-11-06 16:02 UTC by mzweigert

2016-11-06 16:08 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/Address.java
> +    @Length(max = 7)
Wartość `min` też powinna być `7`.

2016-11-06 16:09 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/Address.java
> +    private String zipCode;
`@Length(max = 7, min = 7)`?

2016-11-07 18:33 UTC, m-ciesielski requested changes

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/abstracts/AbstractPersonEntity.java
> +    private Address address;
Na pewno chcemy tutaj `@OneToOne`, a nie `@ManyToOne`? pod jednym adresem może być kilka osób.

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/abstracts/PersonRepository.java
> +@NoRepositoryBean
Brak białej linii po importach.

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/address/Address.java
> +    @Length(max = 7)
`@Length(max = 6, min = 6)` ?

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/car/Car.java
> +    private int year;
Czy `@Length` można stosować przy intach? http://docs.jboss.org/hibernate/stable/validator/api/index.html?org/hibernate/validator/constraints/Length.html

I czy nie lepiej byłoby trzymać to jako `String`?

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/car/Car.java
> +    private int vehicleMileage;
`@Length` na `int`.

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/car/Car.java
> +    private String vin;
`@Length(min = 17, max = 17)`?

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/client/Client.java
> +    private String email;
Regex na email? https://github.com/auto-ckz/auto-ckz/blob/18e12f00304f94d051981f6609c1f54cf2cfaec7/src/main/java/auto_ckz/domain/client/Client.java#L33

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/director/Director.java
> +    private int pesel;
`@Length(min = 11, max = 11)`

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/mechanic/Mechanic.java
> +    private int pesel;
`@Length(min = 11, max = 11)`

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/memberofcustomerservice/MemberOfCustomerService.java
> +   private int pesel;
`@Length(min = 11, max = 11)`

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/repairorder/RepairOrder.java
> +    private Car car;
Czy tu nie powinno być `@ManyToOne`?

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/repairorder/RepairOrder.java
> +    private int totalCost;
J.w. `@Length` na inta.

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/abstracts/AbstractPersonEntity.java
> +    private int phoneNumber;
Nie lepiej trzymać numer telefon jako `String`?

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/car/Car.java
> +    private String make;
Ten String oznacza producenta?

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/carpart/CarPart.java
> +    private int cost;
`@Length` na `int`.

2016-11-07 18:33 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/repairhistory/RepairHistory.java
> +    private int cost;
IMHO `BigDecimal` bardziej by pasował do trzymania kosztów naprawy niż `int`.

2016-11-08 19:34 UTC, dkozlowski22 commented on src/main/java/auto_ckz/domain/abstracts/AbstractPersonEntity.java
> +    private int phoneNumber;
Numer tel musi być jako String, bo wartości mogą wykraczać poza int'a

2016-11-08 19:37 UTC, dkozlowski22 commented on src/main/java/auto_ckz/domain/car/Car.java
> +    private String make;
Tak oznacza markę samochodu i metoda w repository powinna być findByMake() a nie findByModel()

2016-11-08 22:45 UTC, mzweigert commented on src/main/java/auto_ckz/domain/repairorder/RepairOrder.java
> +    private Car car;
Tu chyba nie, bo jedne zlecenie może mieć jeden samochód do naprawy

2016-11-08 22:46 UTC, mzweigert commented on src/main/java/auto_ckz/domain/abstracts/AbstractPersonEntity.java
> +    private Address address;
Po co sobie komplikować życie :)

2016-11-09 16:53 UTC, m-ciesielski requested changes

2016-11-09 16:53 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/repairhistory/RepairHistory.java
> +    private BigDecimal cost;
`@Length` na BigDecimal.

2016-11-09 16:53 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/repairorder/RepairOrderRepository.java
> +    RepairOrder findByCarId(@Param("CarId") Long carId);
`@Param("CarId")` - wszystkie inne parametry zaczynają się z małej litery.

2016-11-09 16:53 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/carpart/CarPart.java
> +    private int cost;
`BigDecimal` zamiast `int`? i przydałoby się `@Range(min = 0, max = 999999)` żeby nie można było wrzucić ujemnego kosztu.

2016-11-09 16:53 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/car/Car.java
> +    private int vehicleMileage;
`@Range(min = 0, max = 9999999)`?

2016-11-09 16:53 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/car/Car.java
> +    private int year;
IMHO lepiej bez `max = 2016`.

2016-11-12 11:10 UTC, m-ciesielski requested changes

2016-11-12 11:10 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/abstracts/AbstractPersonEntity.java
> +    private Long pesel;
`@Length` na `Long`, IMHO pesel powinien być trzymany jako `String`.

2016-11-12 11:10 UTC, m-ciesielski commented on src/main/java/auto_ckz/domain/carpart/CarPartRepository.java
> +public interface CarPartRepository extends PagingAndSortingRepository<Car, Long> { }
`PagingAndSortingRepository<Car, Long>` -> `PagingAndSortingRepository<CarPart, Long>`

2016-11-12 12:19 UTC, m-ciesielski approved these changes
👍

2016-11-12 12:26 UTC, merged